// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-playground/validator/v10"
	"github.com/google/wire"
	"github.com/labstack/echo/v4"
	"timkerjaService/app"
	"timkerjaService/controller"
	"timkerjaService/repository"
	"timkerjaService/service"
)

// Injectors from injector.go:

func InitializedServer() *echo.Echo {
	timKerjaRepositoryImpl := repository.NewTimKerjaRepositoryImpl()
	db := app.GetConnection()
	v := _wireValue
	validate := validator.New(v...)
	timKerjaServiceImpl := service.NewTimKerjaServiceImpl(timKerjaRepositoryImpl, db, validate)
	timKerjaControllerImpl := controller.NewTimKerjaControllerImpl(timKerjaServiceImpl)
	susunanTimRepositoryImpl := repository.NewSusunanTimRepositoryImpl()
	susunanTimServiceImpl := service.NewSusunanTimServiceImpl(susunanTimRepositoryImpl, db, validate)
	susunanTimControllerImpl := controller.NewSusunanTimControllerImpl(susunanTimServiceImpl)
	jabatanTimRepositoryImpl := repository.NewJabatanTimRepositoryImpl()
	jabatanTimServiceImpl := service.NewJabatanTimServiceImpl(jabatanTimRepositoryImpl, db, validate)
	jabatanTimControllerImpl := controller.NewJabatanTimControllerImpl(jabatanTimServiceImpl)
	realisasiAnggaranRepositoryImpl := repository.NewRealisasiAnggaranRepositoryImpl()
	realisasiAnggaranServiceImpl := service.NewRealisasiAnggaranServiceImpl(db, realisasiAnggaranRepositoryImpl)
	realisasiAnggaranControllerImpl := controller.NewRealisasiAnggaranControllerImpl(realisasiAnggaranServiceImpl)
	penilaianKinerjaRepositoryImpl := repository.NewPenilaianKinerjaRepositoryImpl()
	penilaianKinerjaServiceImpl := service.NewPenilaianKinerjaServiceImpl(db, penilaianKinerjaRepositoryImpl, validate)
	penilaianKinerjaControllerImpl := controller.NewPenilaianKinerjaControllerImpl(penilaianKinerjaServiceImpl)
	petugasTimRepositoryImpl := repository.NewPetugasTimRepositoryImpl()
	petugasTimServiceImpl := service.NewPetugasTimServiceImpl(petugasTimRepositoryImpl, susunanTimRepositoryImpl, db, validate)
	petugasTimControllerImpl := controller.NewPetugasTimControllerImpl(petugasTimServiceImpl)
	echoEcho := app.NewRouter(timKerjaControllerImpl, susunanTimControllerImpl, jabatanTimControllerImpl, realisasiAnggaranControllerImpl, penilaianKinerjaControllerImpl, petugasTimControllerImpl)
	return echoEcho
}

var (
	_wireValue = []validator.Option{}
)

// injector.go:

var timKerjaSet = wire.NewSet(repository.NewTimKerjaRepositoryImpl, wire.Bind(new(repository.TimKerjaRepository), new(*repository.TimKerjaRepositoryImpl)), service.NewTimKerjaServiceImpl, wire.Bind(new(service.TimKerjaService), new(*service.TimKerjaServiceImpl)), controller.NewTimKerjaControllerImpl, wire.Bind(new(controller.TimKerjaController), new(*controller.TimKerjaControllerImpl)))

var susunanTimSet = wire.NewSet(repository.NewSusunanTimRepositoryImpl, wire.Bind(new(repository.SusunanTimRepository), new(*repository.SusunanTimRepositoryImpl)), service.NewSusunanTimServiceImpl, wire.Bind(new(service.SusunanTimService), new(*service.SusunanTimServiceImpl)), controller.NewSusunanTimControllerImpl, wire.Bind(new(controller.SusunanTimController), new(*controller.SusunanTimControllerImpl)))

var jabatanTimSet = wire.NewSet(repository.NewJabatanTimRepositoryImpl, wire.Bind(new(repository.JabatanTimRepository), new(*repository.JabatanTimRepositoryImpl)), service.NewJabatanTimServiceImpl, wire.Bind(new(service.JabatanTimService), new(*service.JabatanTimServiceImpl)), controller.NewJabatanTimControllerImpl, wire.Bind(new(controller.JabatanTimController), new(*controller.JabatanTimControllerImpl)))

var realisasiAnggaranSet = wire.NewSet(repository.NewRealisasiAnggaranRepositoryImpl, wire.Bind(new(repository.RealisasiAnggaranRepository), new(*repository.RealisasiAnggaranRepositoryImpl)), service.NewRealisasiAnggaranServiceImpl, wire.Bind(new(service.RealisasiAnggaranService), new(*service.RealisasiAnggaranServiceImpl)), controller.NewRealisasiAnggaranControllerImpl, wire.Bind(new(controller.RealisasiAnggaranController), new(*controller.RealisasiAnggaranControllerImpl)))

var penilaianKinerjaSet = wire.NewSet(repository.NewPenilaianKinerjaRepositoryImpl, wire.Bind(new(repository.PenilaianKinerjaRepository), new(*repository.PenilaianKinerjaRepositoryImpl)), service.NewPenilaianKinerjaServiceImpl, wire.Bind(new(service.PenilaianKinerjaService), new(*service.PenilaianKinerjaServiceImpl)), controller.NewPenilaianKinerjaControllerImpl, wire.Bind(new(controller.PenilaianKinerjaController), new(*controller.PenilaianKinerjaControllerImpl)))

var petugasTimSet = wire.NewSet(repository.NewPetugasTimRepositoryImpl, wire.Bind(new(repository.PetugasTimRepository), new(*repository.PetugasTimRepositoryImpl)), service.NewPetugasTimServiceImpl, wire.Bind(new(service.PetugasTimService), new(*service.PetugasTimServiceImpl)), controller.NewPetugasTimControllerImpl, wire.Bind(new(controller.PetugasTimController), new(*controller.PetugasTimControllerImpl)))
