// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/jabatantim": {
            "get": {
                "description": "Get All Jabatan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jabatan Tim"
                ],
                "summary": "Get All Jabatan Tim",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.JabatanTimResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Jabatan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jabatan Tim"
                ],
                "summary": "Create Jabatan Tim",
                "parameters": [
                    {
                        "description": "Jabatan Tim Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.JabatanTimCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JabatanTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/jabatantim/{id}": {
            "get": {
                "description": "Get Jabatan Tim detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jabatan Tim"
                ],
                "summary": "Get Jabatan Tim by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jabatan Tim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JabatanTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Jabatan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jabatan Tim"
                ],
                "summary": "Update Jabatan Tim",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jabatan Tim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Jabatan Tim Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.JabatanTimUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.JabatanTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Jabatan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jabatan Tim"
                ],
                "summary": "Delete Jabatan Tim",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Jabatan Tim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/laporan_tpp": {
            "get": {
                "description": "Penilaian Kinerja berdasarkan bulan \u0026 tahun plus nilai tpp individu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "TPP"
                ],
                "summary": "Laporan TPP Konker by bulan tahun",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tahun penilaian (ex: 2025)",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bulan penilaian (ex: 12)",
                        "name": "bulan",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.LaporanPenilaianKinerjaResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/only_timkerja": {
            "get": {
                "description": "Get All Tim Kerja",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Get All Tim Kerja",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.TimKerjaResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/penilaian_kinerja": {
            "get": {
                "description": "Penilaian Kinerja berdasarkan bulan \u0026 tahun, dikelompokkan per kode tim dan individu",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Penilaian Kinerja"
                ],
                "summary": "Penilaian kinerja by bulan tahun",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tahun penilaian (ex: 2025)",
                        "name": "tahun",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Bulan penilaian (ex: 12)",
                        "name": "bulan",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.LaporanPenilaianKinerjaResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Add Penilaian to Individu by jenis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Penilaian Kinerja"
                ],
                "summary": "Add New Penialaian to Individu",
                "parameters": [
                    {
                        "description": "Penilaian Tim Kerja Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PenilaianKinerjaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PenilaianKinerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/penilaian_kinerja/:id": {
            "put": {
                "description": "Update Penilaian Individu by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Penilaian Kinerja"
                ],
                "summary": "Update Penialaian Kinerja Individu",
                "parameters": [
                    {
                        "description": "Penilaian Tim Kerja Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PenilaianKinerjaRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PenilaianKinerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/petugas_tim": {
            "post": {
                "description": "Add petugas to the program unggulan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petugas"
                ],
                "summary": "Add Petugas",
                "parameters": [
                    {
                        "description": "Petugas Tim Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.PetugasTimCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.PetugasTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/petugas_tim/:idPetugasTim": {
            "delete": {
                "description": "Remove petugas from the program unggulan assigned",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Petugas"
                ],
                "summary": "Delete Petugas",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Petugas Tim ID",
                        "name": "idPetugasTim",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "DELETED",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/realisasianggaran": {
            "post": {
                "description": "Upsert Realisasi Anggaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Realisasi Anggaran"
                ],
                "summary": "Upsert Realisasi Anggaran",
                "parameters": [
                    {
                        "description": "Realisasi Anggaran Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RealisasiAnggaranCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.RealisasiAnggaranResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/realisasianggaran/detail/{id}": {
            "get": {
                "description": "Get Realisasi Anggaran detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Realisasi Anggaran"
                ],
                "summary": "Get Realisasi Anggaran by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Realisasi Anggaran ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.RealisasiAnggaranResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/realisasianggaran/{id}": {
            "delete": {
                "description": "Delete Realisasi Anggaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Realisasi Anggaran"
                ],
                "summary": "Delete Realisasi Anggaran",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Realisasi Anggaran ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/realisasianggaran/{kode_subkegiatan}/{kode_tim}/{id_rencana_kinerja}/{bulan}/{tahun}": {
            "get": {
                "description": "Get All Realisasi Anggaran",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Realisasi Anggaran"
                ],
                "summary": "Get All Realisasi Anggaran",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Kode Tim",
                        "name": "kode_tim",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID Rencana Kinerja",
                        "name": "id_rencana_kinerja",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Kode Subkegiatan",
                        "name": "kode_subkegiatan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Bulan",
                        "name": "bulan",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Tahun",
                        "name": "tahun",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.RealisasiAnggaranResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/susunantim": {
            "get": {
                "description": "Get All Susunan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Susunan Tim"
                ],
                "summary": "Get All Susunan Tim",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.SusunanTimResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Susunan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Susunan Tim"
                ],
                "summary": "Create Susunan Tim",
                "parameters": [
                    {
                        "description": "Susunan Tim Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SusunanTimCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.SusunanTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/susunantim/{id}": {
            "get": {
                "description": "Get Susunan Tim detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Susunan Tim"
                ],
                "summary": "Get Susunan Tim by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Susunan Tim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.SusunanTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Susunan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Susunan Tim"
                ],
                "summary": "Update Susunan Tim",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Susunan Tim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Susunan Tim Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.SusunanTimUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.SusunanTimResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Susunan Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Susunan Tim"
                ],
                "summary": "Delete Susunan Tim",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Susunan Tim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/susunantim/{kodeTim}/pelaksana": {
            "get": {
                "description": "Get Pelaksana Tim by Kode Tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Susunan Tim"
                ],
                "summary": "Susunan Tim by Kode Tim",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.SusunanTimResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/timkerja": {
            "get": {
                "description": "Get All Tim Kerja with their Susunan Tim details",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Get All Tim Kerja with Details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.TimKerjaDetailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create new Tim Kerja",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Create Tim Kerja",
                "parameters": [
                    {
                        "description": "Tim Kerja Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.TimKerjaCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TimKerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/timkerja-sekretariat": {
            "get": {
                "description": "Get All Tim Kerja sekretariat with susunan tim",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Get All Tim Kerja Sekretariat with Details",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.TimKerjaDetailResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/timkerja/{id}": {
            "get": {
                "description": "Get Tim Kerja detail by ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Get Tim Kerja by ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tim Kerja ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TimKerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Update Tim Kerja",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Update Tim Kerja",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tim Kerja ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tim Kerja Update Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.TimKerjaUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TimKerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete Tim Kerja",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Delete Tim Kerja",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Tim Kerja ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/timkerja/{kodetim}/program_unggulan": {
            "get": {
                "description": "Find all program unggulan to existing tim kerja, multiple",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Find all program unggulan to tim kerja",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/web.ProgramUnggulanTimKerjaResponse"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Delete Rencana Kinerja dari timkerja sekretariat",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Delete Rencana Kinerja",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "RencanaKinerjaTim ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        },
        "/timkerja/{kodetim}/realisasi_pokin": {
            "post": {
                "description": "Save realisasi pokin in Tim Kerja",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tim Kerja"
                ],
                "summary": "Save Realisasi Pokin",
                "parameters": [
                    {
                        "description": "Realisasi Pokin Create Request",
                        "name": "data",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.RealisasiRequest"
                        }
                    },
                    {
                        "type": "string",
                        "description": "Kode Tim",
                        "name": "kodetim",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.WebResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/web.TimKerjaResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internal.PelaksanaPokin": {
            "type": "object",
            "properties": {
                "nama_pelaksana": {
                    "type": "string"
                },
                "nip_pelaksana": {
                    "type": "string"
                },
                "rencana_kinerjas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.RencanaKinerjaAsn"
                    }
                }
            }
        },
        "internal.RencanaKinerjaAsn": {
            "type": "object",
            "properties": {
                "id_rekin": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_bidang_urusan": {
                    "type": "string"
                },
                "kode_program": {
                    "type": "string"
                },
                "kode_subkegiatan": {
                    "type": "string"
                },
                "nama_bidang_urusan": {
                    "type": "string"
                },
                "nama_pelaksana": {
                    "type": "string"
                },
                "nama_program": {
                    "type": "string"
                },
                "nama_subkegiatan": {
                    "type": "string"
                },
                "nip_pelaksana": {
                    "type": "string"
                },
                "pagu": {
                    "type": "integer"
                },
                "rencana_kinerja": {
                    "type": "string"
                },
                "tahapan_pelaksanaan": {
                    "$ref": "#/definitions/internal.WaktuPelaksanaan"
                }
            }
        },
        "internal.TaggingIndikator": {
            "type": "object",
            "properties": {
                "id_indikator": {
                    "type": "string"
                },
                "kode": {
                    "type": "string"
                },
                "nama_indikator": {
                    "type": "string"
                },
                "targets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.TaggingTargetItem"
                    }
                }
            }
        },
        "internal.TaggingPohonKinerjaItem": {
            "type": "object",
            "properties": {
                "faktor_pendorong": {
                    "type": "string"
                },
                "faktor_penghambat": {
                    "type": "string"
                },
                "id_pohon": {
                    "type": "integer"
                },
                "id_tagging": {
                    "type": "integer"
                },
                "indikator": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.TaggingIndikator"
                    }
                },
                "jenis_pohon": {
                    "type": "string"
                },
                "keterangan": {
                    "type": "string"
                },
                "keterangan_tagging": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_program_unggulan": {
                    "type": "string"
                },
                "nama_opd": {
                    "type": "string"
                },
                "nama_pohon": {
                    "type": "string"
                },
                "nama_program_unggulan": {
                    "type": "string"
                },
                "pelaksanas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.PelaksanaPokin"
                    }
                },
                "realisasi_anggaran": {
                    "type": "integer"
                },
                "rekomendasi_tl": {
                    "type": "string"
                },
                "rencana_aksi": {
                    "type": "string"
                },
                "rencana_implementasi": {
                    "type": "string"
                },
                "risiko_hukum": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                }
            }
        },
        "internal.TaggingTargetItem": {
            "type": "object",
            "properties": {
                "id_target": {
                    "type": "string"
                },
                "indikator_id": {
                    "type": "string"
                },
                "satuan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                },
                "target": {
                    "type": "string"
                }
            }
        },
        "internal.WaktuPelaksanaan": {
            "type": "object",
            "properties": {
                "tw_1": {
                    "type": "integer"
                },
                "tw_2": {
                    "type": "integer"
                },
                "tw_3": {
                    "type": "integer"
                },
                "tw_4": {
                    "type": "integer"
                }
            }
        },
        "web.JabatanTimCreateRequest": {
            "type": "object",
            "properties": {
                "level_jabatan": {
                    "type": "integer"
                },
                "nama_jabatan": {
                    "type": "string"
                }
            }
        },
        "web.JabatanTimResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "level_jabatan": {
                    "type": "integer"
                },
                "nama_jabatan": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "web.JabatanTimUpdateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "level_jabatan": {
                    "type": "integer"
                },
                "nama_jabatan": {
                    "type": "string"
                }
            }
        },
        "web.LaporanPenilaianKinerjaResponse": {
            "type": "object",
            "required": [
                "kode_tim",
                "nama_tim"
            ],
            "properties": {
                "is_sekretariat": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_tim": {
                    "type": "string"
                },
                "penilaian_kinerjas": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.PenilaianGroupedResponse"
                    }
                }
            }
        },
        "web.PenilaianGroupedResponse": {
            "type": "object",
            "properties": {
                "bulan": {
                    "type": "integer"
                },
                "golongan": {
                    "type": "string"
                },
                "id_pegawai": {
                    "type": "string"
                },
                "jenis_jabatan": {
                    "type": "string"
                },
                "kinerja_bappeda": {
                    "type": "integer"
                },
                "kinerja_person": {
                    "type": "integer"
                },
                "kinerja_tim": {
                    "type": "integer"
                },
                "kode_tim": {
                    "type": "string"
                },
                "level_jabatan_tim": {
                    "type": "integer"
                },
                "nama_jabatan_tim": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nilai_akhir": {
                    "type": "integer"
                },
                "pangkat": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "tpp_pegawai": {
                    "$ref": "#/definitions/web.PenilaianTppExtension"
                }
            }
        },
        "web.PenilaianKinerjaRequest": {
            "type": "object",
            "required": [
                "bulan",
                "id_pegawai",
                "jenis_nilai",
                "kode_opd",
                "kode_tim",
                "nilai_kinerja",
                "tahun"
            ],
            "properties": {
                "bulan": {
                    "type": "integer"
                },
                "id_pegawai": {
                    "type": "string"
                },
                "jenis_nilai": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nilai_kinerja": {
                    "type": "integer"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.PenilaianKinerjaResponse": {
            "type": "object",
            "required": [
                "bulan",
                "id_pegawai",
                "jenis_nilai",
                "kode_opd",
                "kode_tim",
                "nilai_kinerja",
                "tahun"
            ],
            "properties": {
                "bulan": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "created_by": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_pegawai": {
                    "type": "string"
                },
                "jenis_nilai": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_jabatan_tim": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nilai_kinerja": {
                    "type": "integer"
                },
                "tahun": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "web.PenilaianTppExtension": {
            "type": "object",
            "properties": {
                "jumlah_bersih": {
                    "type": "integer"
                },
                "jumlah_kotor": {
                    "type": "integer"
                },
                "jumlah_pajak": {
                    "type": "integer"
                },
                "pajak": {
                    "type": "number"
                },
                "persentase_penerimaan": {
                    "type": "string"
                },
                "potongan_bpjs": {
                    "type": "number"
                },
                "tpp_basic": {
                    "type": "integer"
                }
            }
        },
        "web.PetugasTimCreateRequest": {
            "type": "object",
            "required": [
                "id_program_unggulan",
                "kode_tim",
                "pegawai_id",
                "tahun"
            ],
            "properties": {
                "bulan": {
                    "type": "integer"
                },
                "id_program_unggulan": {
                    "type": "integer"
                },
                "kode_tim": {
                    "type": "string"
                },
                "pegawai_id": {
                    "type": "string"
                },
                "tahun": {
                    "type": "integer"
                }
            }
        },
        "web.PetugasTimResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "pegawai_id": {
                    "description": "nip",
                    "type": "string"
                }
            }
        },
        "web.ProgramUnggulanTimKerjaResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "id_program_unggulan": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_program_unggulan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "pohon_kinerja": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/internal.TaggingPohonKinerjaItem"
                    }
                },
                "program_unggulan": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.RealisasiAnggaranCreateRequest": {
            "type": "object",
            "required": [
                "bulan",
                "id_pohon",
                "id_rencana_kinerja",
                "kode_opd",
                "kode_subkegiatan",
                "kode_tim",
                "realisasi_anggaran",
                "tahun"
            ],
            "properties": {
                "bukti_dukung": {
                    "type": "string"
                },
                "bulan": {
                    "type": "integer"
                },
                "faktor_pendorong": {
                    "type": "string"
                },
                "faktor_penghambat": {
                    "type": "string"
                },
                "id_pohon": {
                    "type": "integer"
                },
                "id_program_unggulan": {
                    "type": "integer"
                },
                "id_rencana_kinerja": {
                    "type": "string"
                },
                "id_rencana_kinerja_sekretariat": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_subkegiatan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "realisasi_anggaran": {
                    "type": "integer"
                },
                "rekomendasi_tl": {
                    "type": "string"
                },
                "rencana_aksi": {
                    "type": "string"
                },
                "risiko_hukum": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.RealisasiAnggaranResponse": {
            "type": "object",
            "required": [
                "id_pohon"
            ],
            "properties": {
                "bukti_dukung": {
                    "type": "string"
                },
                "bulan": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "faktor_pendorong": {
                    "type": "string"
                },
                "faktor_penghambat": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_pohon": {
                    "type": "integer"
                },
                "id_program_unggulan": {
                    "type": "integer"
                },
                "id_rencana_kinerja": {
                    "type": "string"
                },
                "id_rencana_kinerja_sekretariat": {
                    "type": "integer"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_subkegiatan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "realisasi_anggaran": {
                    "type": "integer"
                },
                "rekomendasi_tl": {
                    "type": "string"
                },
                "rencana_aksi": {
                    "type": "string"
                },
                "risiko_hukum": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "web.RealisasiRequest": {
            "type": "object",
            "required": [
                "id_pokin",
                "jenis_item",
                "jenis_pohon",
                "kode_item",
                "kode_opd",
                "kode_tim",
                "nama_item",
                "tahun"
            ],
            "properties": {
                "faktor_pendorong": {
                    "type": "string"
                },
                "faktor_penghambat": {
                    "type": "string"
                },
                "id_pokin": {
                    "type": "integer"
                },
                "jenis_item": {
                    "type": "string"
                },
                "jenis_pohon": {
                    "type": "string"
                },
                "kode_item": {
                    "type": "string"
                },
                "kode_opd": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_item": {
                    "type": "string"
                },
                "pagu": {
                    "type": "integer",
                    "minimum": 0
                },
                "realisasi": {
                    "type": "integer",
                    "minimum": 0
                },
                "rtl": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "url_bukti_dukung": {
                    "type": "string"
                }
            }
        },
        "web.SusunanTimCreateRequest": {
            "type": "object",
            "required": [
                "id_jabatan_tim",
                "kode_tim",
                "nama_jabatan_tim",
                "nama_pegawai",
                "nip"
            ],
            "properties": {
                "id_jabatan_tim": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_jabatan_tim": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                }
            }
        },
        "web.SusunanTimDetailResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "level_jabatan": {
                    "type": "integer"
                },
                "nama_jabatan": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                }
            }
        },
        "web.SusunanTimResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "id_jabatan_tim": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_jabatan_tim": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "web.SusunanTimUpdateRequest": {
            "type": "object",
            "required": [
                "id_jabatan_tim",
                "kode_tim",
                "nama_jabatan_tim",
                "nama_pegawai",
                "nip"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "id_jabatan_tim": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_jabatan_tim": {
                    "type": "string"
                },
                "nama_pegawai": {
                    "type": "string"
                },
                "nip": {
                    "type": "string"
                }
            }
        },
        "web.TimKerjaCreateRequest": {
            "type": "object",
            "properties": {
                "is_active": {
                    "type": "boolean"
                },
                "is_sekretariat": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "nama_tim": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.TimKerjaDetailResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_sekretariat": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_tim": {
                    "type": "string"
                },
                "susunan_tims": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.SusunanTimDetailResponse"
                    }
                }
            }
        },
        "web.TimKerjaResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_sekretariat": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "kode_tim": {
                    "type": "string"
                },
                "nama_tim": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "web.TimKerjaUpdateRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                },
                "is_active": {
                    "type": "boolean"
                },
                "is_sekretariat": {
                    "type": "boolean"
                },
                "keterangan": {
                    "type": "string"
                },
                "nama_tim": {
                    "type": "string"
                },
                "tahun": {
                    "type": "string"
                }
            }
        },
        "web.WebResponse": {
            "description": "Web Response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${HOST}:${PORT}",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Tim Kerja Service API",
	Description:      "API For Tim Kerja Services",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
